### ISSUE TITLE
lintチェック警告

### ISSUE THREAD

**Issue by shindo-n** [automation-coe-study/ansible_cicd_lint#3]
本リポジトリのlintチェックを使用してみたところ、以下の警告がでます。
![image](https://github.com/user-attachments/assets/23f18773-26f1-4eff-9488-040c8bb3c5d4)
https://github.com/automation-coe-study/ansible_role_create_dir_linux/actions/runs/10296908395
警告の3番目、先頭行に"---"を付ける。について修正対応いただけますでしょうか。

また、8/20相談会で話に上がった4番目の警告の修正については、確認したところ対応ができないものでした。ご放念ください。
(github actionsにてトリガーを指定する "on: " の記載が真偽値として判定され、true/falseにしたほうがよいという内容でした。)

**Comment by shindo-n** [comment]
@daizo-chino ご対応ありがとうございます。
再実行したところ警告が表示されなくなりました。
![image](https://github.com/user-attachments/assets/6f449d45-545e-4804-8eb7-ecc8a4828274)
https://github.com/automation-coe-study/ansible_role_create_dir_linux/actions/runs/10482455482

すみません、初めにご指摘すべきだったのですが、上記1つめの警告についても本レポジトリのlint.yml内の記載によるもののようです。
https://dev.classmethod.jp/articles/github-actions-checkout-action-v4-released/
`actions/checkout@v3`で使われているNode.js 16 は昨年 11 月に EOL を迎えているため非推奨（Deprecated）であるという警告のため、
このタイミングで合わせてv4にアップデートいただけますでしょうか。

**Comment by daizo-chino** [comment]
修正後、動作確認OKのため当Issueはクローズします。
